// <auto-generated />
using System;
using EveUtils.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EveUtils.Migrations.Client.Sqlite.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    [Migration("20260904225216_AddFleetMemberAvailability")]
    partial class AddFleetMemberAvailability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("EveUtils.Shared.Identity.LocalCharacter", b =>
                {
                    b.Property<int>("EsiCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrantedScopesJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("EsiCharacterId");

                    b.HasIndex("SortOrder");

                    b.ToTable("LocalCharacter");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fittings.Entities.LocalFitting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EsiFittingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShipTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("OwnerId", "EsiFittingId")
                        .IsUnique();

                    b.ToTable("LocalFitting");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Composition.FleetComposition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClientOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerCharacterId");

                    b.ToTable("FleetComposition");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Composition.FleetCompositionEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EntryMinCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("FleetCompositionEntry");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Composition.FleetCompositionRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CompositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupMinCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompositionId");

                    b.ToTable("FleetCompositionRole");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.CachedExternalCharacter", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alliance")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Corp")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FetchedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.ToTable("CachedExternalCharacter");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.Fleet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Activation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatorCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsiAutoApplyStructure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsiAutoInviteMembers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EsiFleetBossId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EsiFleetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EsiSyncState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FleetCompositionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FromTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClientOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFreeMove")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVoiceEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motd")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("OfflineBehavior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ToTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatorCharacterId");

                    b.HasIndex("Visibility", "State");

                    b.ToTable("Fleet");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetInvite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FleetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InviteeCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InviterCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SquadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("WingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.HasIndex("InviteeCharacterId", "Status");

                    b.ToTable("FleetInvite");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetJoinRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FleetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequesterCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RespondedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FleetId", "Status");

                    b.HasIndex("RequesterCharacterId", "Status");

                    b.ToTable("FleetJoinRequest");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AssignedCompositionEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailabilityNote")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AvailabilityUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EsiMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FitSkillVerdict")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FleetId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("JoinTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShipTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SolarSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SquadId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TakesFleetWarp")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FleetId");

                    b.HasIndex("FleetId", "CharacterId")
                        .IsUnique();

                    b.ToTable("FleetMember");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetSquad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EsiSquadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("WingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WingId");

                    b.ToTable("FleetSquad");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetWing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EsiWingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FleetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.ToTable("FleetWing");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Gamelog.Entities.CharacterMetricState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BountyTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinedJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterName")
                        .IsUnique();

                    b.ToTable("CharacterMetricState");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Gamelog.Entities.CombatSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Timestamp");

                    b.ToTable("CombatSample");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Implants.Entities.CharacterImplant", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImplantTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "ImplantTypeId");

                    b.ToTable("CharacterImplant");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Market.Entities.LocalMarketPrice", b =>
                {
                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AdjustedPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("AveragePrice")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TypeId");

                    b.ToTable("LocalMarketPrice");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Messaging.Entities.ClientInboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipientCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RefId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SenderCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerAddress")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("ServerMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipientCharacterId", "ServerMessageId")
                        .IsUnique();

                    b.ToTable("ClientInboxMessage");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.ActivitySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityKind")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BountyIsk")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CompletenessUnknown")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyTypeCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExpectedPayoutIsk")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("LootEntriesWithoutPrice")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LootIskGained")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LootIskLost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LootIskNet")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("LootItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LootVolume")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayoutEligibleCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RunsIncluded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SolarSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceRevisionSum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StoppedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupCode")
                        .IsUnique();

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("ActivitySummary");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityKind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AutoSavedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FitContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FitNameSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FormerGroupCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsParticipant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPayoutEligible")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPushedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LootStrategy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MissionLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SavedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiteTypeSource")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SolarSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StoppedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncServerAddress")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimesCorrectedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupCode", "CharacterId");

                    b.ToTable("Run");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunBountyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Isk")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("RunBountyEntry");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunEnemyObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("EnemyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("RunEnemyObservation");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunLootCapture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("RunLootCapture");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunLootEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ClipboardPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LootKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunLootCaptureId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunLootCaptureId");

                    b.ToTable("RunLootEntry");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BonusWindowSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParameterKey")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypedValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("RunParameter");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Settings.Entities.ClientSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ClientSetting");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Fitting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShipId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("Fitting");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ship");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Skills.Entities.CharacterAttributes", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Memory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Perception")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Willpower")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId");

                    b.ToTable("CharacterAttributes");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Skills.Entities.CharacterSkill", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "SkillTypeId");

                    b.ToTable("CharacterSkill");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Skills.Entities.CharacterSkillQueueEntry", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinishedLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "QueuePosition");

                    b.ToTable("CharacterSkillQueueEntry");
                });

            modelBuilder.Entity("EveUtils.Shared.Transport.ClientServerSession", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("SavedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Address", "CharacterId");

                    b.ToTable("ClientServerSession");
                });

            modelBuilder.Entity("EveUtils.Shared.Transport.CoupledServer", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CertFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Address");

                    b.ToTable("CoupledServer");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Composition.FleetCompositionEntry", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Composition.FleetCompositionRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EveUtils.Shared.Modules.Fleet.Composition.FitReference", "Fit", b1 =>
                        {
                            b1.Property<long>("FleetCompositionEntryId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ContentHash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FitName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<int?>("LocalFittingId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("RawJson")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ServerSharedFitId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShipTypeId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FleetCompositionEntryId");

                            b1.ToTable("FleetCompositionEntry");

                            b1.WithOwner()
                                .HasForeignKey("FleetCompositionEntryId");
                        });

                    b.Navigation("Fit")
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Composition.FleetCompositionRole", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Composition.FleetComposition", null)
                        .WithMany()
                        .HasForeignKey("CompositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetInvite", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetJoinRequest", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetMember", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EveUtils.Shared.Modules.Fleet.Composition.FitReference", "AssignedFit", b1 =>
                        {
                            b1.Property<long>("FleetMemberId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ContentHash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FitName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<int?>("LocalFittingId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("RawJson")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ServerSharedFitId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShipTypeId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FleetMemberId");

                            b1.ToTable("FleetMember");

                            b1.WithOwner()
                                .HasForeignKey("FleetMemberId");
                        });

                    b.Navigation("AssignedFit");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetSquad", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.FleetWing", null)
                        .WithMany()
                        .HasForeignKey("WingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetWing", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunBountyEntry", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Runs.Entities.Run", "Run")
                        .WithMany("BountyEntries")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunEnemyObservation", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Runs.Entities.Run", "Run")
                        .WithMany("EnemyObservations")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunLootCapture", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Runs.Entities.Run", "Run")
                        .WithMany("LootCaptures")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunLootEntry", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Runs.Entities.RunLootCapture", "RunLootCapture")
                        .WithMany("Entries")
                        .HasForeignKey("RunLootCaptureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunLootCapture");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunParameter", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Runs.Entities.Run", "Run")
                        .WithMany("Parameters")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Fitting", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Ships.Entities.Ship", "Ship")
                        .WithMany("Fittings")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.Run", b =>
                {
                    b.Navigation("BountyEntries");

                    b.Navigation("EnemyObservations");

                    b.Navigation("LootCaptures");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunLootCapture", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Ship", b =>
                {
                    b.Navigation("Fittings");
                });
#pragma warning restore 612, 618
        }
    }
}
