// <auto-generated />
using System;
using EveUtils.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EveUtils.Migrations.Client.Sqlite.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    [Migration("20260603091642_AddClientInbox")]
    partial class AddClientInbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EveUtils.Shared.Identity.LocalCharacter", b =>
                {
                    b.Property<int>("EsiCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrantedScopesJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("EsiCharacterId");

                    b.ToTable("LocalCharacter");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fittings.Entities.LocalFitting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EsiFittingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShipTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "EsiFittingId")
                        .IsUnique();

                    b.ToTable("LocalFitting");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Gamelog.Entities.CharacterMetricState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BountyTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinedJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterName")
                        .IsUnique();

                    b.ToTable("CharacterMetricState");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Gamelog.Entities.CombatSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Timestamp");

                    b.ToTable("CombatSample");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Messaging.Entities.ClientInboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipientCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RefId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SenderCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ServerMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipientCharacterId", "ServerMessageId")
                        .IsUnique();

                    b.ToTable("ClientInboxMessage");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Settings.Entities.ClientSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ClientSetting");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Fitting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShipId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("Fitting");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ship");
                });

            modelBuilder.Entity("EveUtils.Shared.Transport.ClientServerSession", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("SavedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Address", "CharacterId");

                    b.ToTable("ClientServerSession");
                });

            modelBuilder.Entity("EveUtils.Shared.Transport.CoupledServer", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CertFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Address");

                    b.ToTable("CoupledServer");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Fitting", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Ships.Entities.Ship", "Ship")
                        .WithMany("Fittings")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Ship", b =>
                {
                    b.Navigation("Fittings");
                });
#pragma warning restore 612, 618
        }
    }
}
