// <auto-generated />
using System;
using EveUtils.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EveUtils.Migrations.Server.SqlServer.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260602183014_AddCharacterMetricState")]
    partial class AddCharacterMetricState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EveUtils.Shared.Modules.Fittings.Entities.SharedFit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EsiFittingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SharedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SharedByCharacterId")
                        .HasColumnType("int");

                    b.Property<string>("SharedByCharacterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ShipTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SharedFit");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.Fleet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorCharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("EsiFleetBossId")
                        .HasColumnType("int");

                    b.Property<long?>("EsiFleetId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("FromTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsFreeMove")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVoiceEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Motd")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OfflineBehavior")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ToTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorCharacterId");

                    b.HasIndex("Visibility", "State");

                    b.ToTable("Fleet");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetInvite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FleetId")
                        .HasColumnType("bigint");

                    b.Property<int>("InviteeCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("InviterCharacterId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<long?>("SquadId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("WingId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.HasIndex("InviteeCharacterId", "Status");

                    b.ToTable("FleetInvite");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<long>("FleetId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("JoinTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("ShipTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SolarSystemId")
                        .HasColumnType("int");

                    b.Property<long>("SquadId")
                        .HasColumnType("bigint");

                    b.Property<bool>("TakesFleetWarp")
                        .HasColumnType("bit");

                    b.Property<long>("WingId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FleetId");

                    b.HasIndex("FleetId", "CharacterId")
                        .IsUnique();

                    b.ToTable("FleetMember");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetSquad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("WingId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WingId");

                    b.ToTable("FleetSquad");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetWing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FleetId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.ToTable("FleetWing");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Gamelog.Entities.CharacterMetricState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BountyTotal")
                        .HasColumnType("bigint");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Kills")
                        .HasColumnType("int");

                    b.Property<string>("MinedJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterName")
                        .IsUnique();

                    b.ToTable("CharacterMetricState");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Gamelog.Entities.CombatSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Timestamp");

                    b.ToTable("CombatSample");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Permissions.Entities.PermissionToggle", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.HasKey("Code");

                    b.ToTable("PermissionToggle");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.ServerAuth.Entities.AllowedCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("EsiCharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("AllowedCharacter");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.ServerAuth.Entities.ServerSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastHeartbeat")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RefreshExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SyncedCharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenHash");

                    b.HasIndex("RefreshTokenHash");

                    b.HasIndex("SyncedCharacterId");

                    b.ToTable("ServerSession");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.ServerAuth.Entities.SyncedCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EsiCharacterId")
                        .HasColumnType("int");

                    b.Property<string>("GrantedScopesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("PairedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RefreshTokenCipher")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("RefreshTokenNonce")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("RefreshTokenTag")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("EsiCharacterId")
                        .IsUnique();

                    b.ToTable("SyncedCharacter");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Fitting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("Fitting");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Mass")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Ship");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Sync.Entities.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("SyncedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("SyncLog");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetInvite", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetMember", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetSquad", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.FleetWing", null)
                        .WithMany()
                        .HasForeignKey("WingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetWing", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.ServerAuth.Entities.ServerSession", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.ServerAuth.Entities.SyncedCharacter", "SyncedCharacter")
                        .WithMany()
                        .HasForeignKey("SyncedCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncedCharacter");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Fitting", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Ships.Entities.Ship", "Ship")
                        .WithMany("Fittings")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Ship", b =>
                {
                    b.Navigation("Fittings");
                });
#pragma warning restore 612, 618
        }
    }
}
