// <auto-generated />
using System;
using EveUtils.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EveUtils.Migrations.Server.Sqlite.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260902100848_MergeRunEnemyObservationsByType")]
    partial class MergeRunEnemyObservationsByType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("EveUtils.Shared.Modules.AdminAuth.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("AdminUser");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.AdminAuth.Entities.AdminUserRole", b =>
                {
                    b.Property<int>("AdminUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdminUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AdminUserRole");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.AdminAuth.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.AdminAuth.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "PermissionCode");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.ApiKeys.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.ToTable("ApiKey");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Backup.Entities.BackupDownload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BackupDownload");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fittings.Entities.SharedFit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("EsiFittingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SharedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SharedByCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SharedByCharacterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShipTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.ToTable("SharedFit");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Composition.FleetComposition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerCharacterId");

                    b.ToTable("FleetComposition");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Composition.FleetCompositionEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EntryMinCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("FleetCompositionEntry");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Composition.FleetCompositionRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CompositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupMinCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompositionId");

                    b.ToTable("FleetCompositionRole");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.Fleet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Activation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatorCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsiAutoApplyStructure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsiAutoInviteMembers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EsiFleetBossId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EsiFleetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EsiSyncState")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FleetCompositionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FromTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFreeMove")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVoiceEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motd")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("OfflineBehavior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ToTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatorCharacterId");

                    b.HasIndex("Visibility", "State");

                    b.ToTable("Fleet");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetInvite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FleetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InviteeCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InviterCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SquadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("WingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.HasIndex("InviteeCharacterId", "Status");

                    b.ToTable("FleetInvite");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetJoinRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FleetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequesterCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RespondedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FleetId", "Status");

                    b.HasIndex("RequesterCharacterId", "Status");

                    b.ToTable("FleetJoinRequest");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AssignedCompositionEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EsiMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FitSkillVerdict")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FleetId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("JoinTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShipTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SolarSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SquadId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TakesFleetWarp")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FleetId");

                    b.HasIndex("FleetId", "CharacterId")
                        .IsUnique();

                    b.ToTable("FleetMember");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetSquad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EsiSquadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("WingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WingId");

                    b.ToTable("FleetSquad");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetWing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EsiWingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FleetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.ToTable("FleetWing");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Gamelog.Entities.CharacterMetricState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BountyTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinedJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterName")
                        .IsUnique();

                    b.ToTable("CharacterMetricState");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Gamelog.Entities.CombatSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Timestamp");

                    b.ToTable("CombatSample");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Messaging.Entities.QueuedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipientCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RefId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SenderCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("RecipientCharacterId", "Status");

                    b.ToTable("QueuedMessage");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Permissions.Entities.PermissionToggle", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("PermissionToggle");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityKind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FitContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FitNameSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FormerGroupCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsParticipant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPayoutEligible")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPushedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SavedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SolarSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StoppedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupCode", "CharacterId");

                    b.ToTable("Run");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunBountyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Isk")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("RunBountyEntry");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunEnemyObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("EnemyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("RunEnemyObservation");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunLootCapture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("RunLootCapture");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunLootEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ClipboardPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LootKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunLootCaptureId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunLootCaptureId");

                    b.ToTable("RunLootEntry");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParameterKey")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypedValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("RunParameter");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.ServerAuth.Entities.AllowedCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EsiCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AllowedCharacter");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.ServerAuth.Entities.ServerSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastHeartbeat")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RefreshExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncedCharacterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenHash");

                    b.HasIndex("RefreshTokenHash");

                    b.HasIndex("SyncedCharacterId");

                    b.ToTable("ServerSession");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.ServerAuth.Entities.SyncedCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("EsiCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrantedScopesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PairedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RefreshTokenCipher")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RefreshTokenNonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RefreshTokenTag")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("EsiCharacterId")
                        .IsUnique();

                    b.ToTable("SyncedCharacter");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Fitting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShipId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("Fitting");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ship");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Sync.Entities.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncLog");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.AdminAuth.Entities.AdminUserRole", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.AdminAuth.Entities.AdminUser", "AdminUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EveUtils.Shared.Modules.AdminAuth.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.AdminAuth.Entities.RolePermission", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.AdminAuth.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Composition.FleetCompositionEntry", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Composition.FleetCompositionRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EveUtils.Shared.Modules.Fleet.Composition.FitReference", "Fit", b1 =>
                        {
                            b1.Property<long>("FleetCompositionEntryId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ContentHash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FitName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<int?>("LocalFittingId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("RawJson")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ServerSharedFitId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShipTypeId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FleetCompositionEntryId");

                            b1.ToTable("FleetCompositionEntry");

                            b1.WithOwner()
                                .HasForeignKey("FleetCompositionEntryId");
                        });

                    b.Navigation("Fit")
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Composition.FleetCompositionRole", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Composition.FleetComposition", null)
                        .WithMany()
                        .HasForeignKey("CompositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetInvite", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetJoinRequest", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetMember", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EveUtils.Shared.Modules.Fleet.Composition.FitReference", "AssignedFit", b1 =>
                        {
                            b1.Property<long>("FleetMemberId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ContentHash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FitName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<int?>("LocalFittingId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("RawJson")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ServerSharedFitId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShipTypeId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FleetMemberId");

                            b1.ToTable("FleetMember");

                            b1.WithOwner()
                                .HasForeignKey("FleetMemberId");
                        });

                    b.Navigation("AssignedFit");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetSquad", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.FleetWing", null)
                        .WithMany()
                        .HasForeignKey("WingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Fleet.Entities.FleetWing", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Fleet.Entities.Fleet", null)
                        .WithMany()
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunBountyEntry", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Runs.Entities.Run", "Run")
                        .WithMany("BountyEntries")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunEnemyObservation", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Runs.Entities.Run", "Run")
                        .WithMany("EnemyObservations")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunLootCapture", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Runs.Entities.Run", "Run")
                        .WithMany("LootCaptures")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunLootEntry", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Runs.Entities.RunLootCapture", "RunLootCapture")
                        .WithMany("Entries")
                        .HasForeignKey("RunLootCaptureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunLootCapture");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunParameter", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Runs.Entities.Run", "Run")
                        .WithMany("Parameters")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.ServerAuth.Entities.ServerSession", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.ServerAuth.Entities.SyncedCharacter", "SyncedCharacter")
                        .WithMany()
                        .HasForeignKey("SyncedCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncedCharacter");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Fitting", b =>
                {
                    b.HasOne("EveUtils.Shared.Modules.Ships.Entities.Ship", "Ship")
                        .WithMany("Fittings")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.AdminAuth.Entities.AdminUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.AdminAuth.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.Run", b =>
                {
                    b.Navigation("BountyEntries");

                    b.Navigation("EnemyObservations");

                    b.Navigation("LootCaptures");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Runs.Entities.RunLootCapture", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("EveUtils.Shared.Modules.Ships.Entities.Ship", b =>
                {
                    b.Navigation("Fittings");
                });
#pragma warning restore 612, 618
        }
    }
}
